// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingIntelligence.Infrastructure.Data;

#nullable disable

namespace TradingIntelligence.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313222540_AddPaperTradingTables")]
    partial class AddPaperTradingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingIntelligence.Core.Entities.BrokerTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<decimal?>("FilledPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LotSize")
                        .HasColumnType("numeric");

                    b.Property<string>("Mt5Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Mt5Ticket")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaperTradeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrokerStatus");

                    b.HasIndex("PaperTradeId")
                        .IsUnique();

                    b.ToTable("BrokerTrades");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.MomentumScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiAnalysis")
                        .HasColumnType("text");

                    b.Property<decimal>("NewsScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("OptionsScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RedditScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RiskFactors")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Session")
                        .HasColumnType("integer");

                    b.Property<string>("SignalSummary")
                        .HasColumnType("text");

                    b.Property<int?>("TickerId")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TradeBias")
                        .HasColumnType("integer");

                    b.Property<string>("TradeSetup")
                        .HasColumnType("text");

                    b.Property<decimal>("VolumeScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.HasIndex("TickerSymbol", "ScoredAt");

                    b.ToTable("MomentumScores");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.OtpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.PaperTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("MomentumScoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PnlPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PnlPoints")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalScoreAtEntry")
                        .HasColumnType("numeric");

                    b.Property<int>("TradeBias")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MomentumScoreId")
                        .IsUnique();

                    b.ToTable("PaperTrades");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.SignalAccuracy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgPnlPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AvgScoreAtEntry")
                        .HasColumnType("numeric");

                    b.Property<int>("Breakevens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TickerSymbol")
                        .IsUnique();

                    b.ToTable("SignalAccuracies");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.SignalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("SignalScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SignalType")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TickerId")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.HasIndex("TickerSymbol", "DetectedAt");

                    b.ToTable("SignalEvents");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.Ticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Exchange")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Tickers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "NVIDIA Corporation",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Microsoft Corporation",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Tesla Inc",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Amazon.com Inc",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Meta Platforms Inc",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "META"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Alphabet Inc",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Advanced Micro Devices",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "AMD"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "SPDR S&P 500 ETF",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NYSE",
                            IsActive = true,
                            Symbol = "SPY"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Invesco QQQ Trust",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "QQQ"
                        });
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("AlertThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TickerSymbol")
                        .IsUnique();

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("TradingIntelligence.Infrastructure.Data.OtpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("OtpCode");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.BrokerTrade", b =>
                {
                    b.HasOne("TradingIntelligence.Core.Entities.PaperTrade", "PaperTrade")
                        .WithOne("BrokerTrade")
                        .HasForeignKey("TradingIntelligence.Core.Entities.BrokerTrade", "PaperTradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaperTrade");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.MomentumScore", b =>
                {
                    b.HasOne("TradingIntelligence.Core.Entities.Ticker", "Ticker")
                        .WithMany("MomentumScores")
                        .HasForeignKey("TickerId");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.PaperTrade", b =>
                {
                    b.HasOne("TradingIntelligence.Core.Entities.MomentumScore", "MomentumScore")
                        .WithMany()
                        .HasForeignKey("MomentumScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MomentumScore");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.SignalEvent", b =>
                {
                    b.HasOne("TradingIntelligence.Core.Entities.Ticker", "Ticker")
                        .WithMany("SignalEvents")
                        .HasForeignKey("TickerId");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.Watchlist", b =>
                {
                    b.HasOne("TradingIntelligence.Core.Entities.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.PaperTrade", b =>
                {
                    b.Navigation("BrokerTrade");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.Ticker", b =>
                {
                    b.Navigation("MomentumScores");

                    b.Navigation("SignalEvents");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.User", b =>
                {
                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
