// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingIntelligence.Infrastructure.Data;

#nullable disable

namespace TradingIntelligence.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradingIntelligence.Core.Entities.MomentumScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiAnalysis")
                        .HasColumnType("text");

                    b.Property<decimal>("NewsScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("OptionsScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RedditScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RiskFactors")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Session")
                        .HasColumnType("integer");

                    b.Property<string>("SignalSummary")
                        .HasColumnType("text");

                    b.Property<int?>("TickerId")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TradeBias")
                        .HasColumnType("integer");

                    b.Property<string>("TradeSetup")
                        .HasColumnType("text");

                    b.Property<decimal>("VolumeScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.HasIndex("TickerSymbol", "ScoredAt");

                    b.ToTable("MomentumScores");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.SignalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("SignalScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SignalType")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TickerId")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TickerId");

                    b.HasIndex("TickerSymbol", "DetectedAt");

                    b.ToTable("SignalEvents");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.Ticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Exchange")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Tickers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(3533),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "NVIDIA Corporation",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5633),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Microsoft Corporation",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5641),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Tesla Inc",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5642),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Amazon.com Inc",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5643),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Meta Platforms Inc",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5644),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "META"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Alphabet Inc",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5646),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Advanced Micro Devices",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5648),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "AMD"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "SPDR S&P 500 ETF",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5649),
                            Exchange = "NYSE",
                            IsActive = true,
                            Symbol = "SPY"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Invesco QQQ Trust",
                            CreatedAt = new DateTime(2026, 3, 11, 21, 3, 27, 876, DateTimeKind.Utc).AddTicks(5650),
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Symbol = "QQQ"
                        });
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("AlertThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TickerSymbol")
                        .IsUnique();

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.MomentumScore", b =>
                {
                    b.HasOne("TradingIntelligence.Core.Entities.Ticker", "Ticker")
                        .WithMany("MomentumScores")
                        .HasForeignKey("TickerId");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.SignalEvent", b =>
                {
                    b.HasOne("TradingIntelligence.Core.Entities.Ticker", "Ticker")
                        .WithMany("SignalEvents")
                        .HasForeignKey("TickerId");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.Watchlist", b =>
                {
                    b.HasOne("TradingIntelligence.Core.Entities.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.Ticker", b =>
                {
                    b.Navigation("MomentumScores");

                    b.Navigation("SignalEvents");
                });

            modelBuilder.Entity("TradingIntelligence.Core.Entities.User", b =>
                {
                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
